### PR TITLE
Add OpenSSL crypto dependencies

### PR DESCRIPTION
**Pull request by CelticMinstrel**
These are the new dependencies for wesnoth/wesnoth#990. I took them from my copy of OpenSSL which I think is a year or two old, and included only the specific headers and libs needed to compile, rather than the whole of OpenSSL.

Obviously this shouldn't be merged until that PR is. Versions of this for VC14 and VC15 are probably not within my ability since I don't have either installed.

### CODE REVIEW

**Comment by gfgtdf** [comment]
do there libs only work with vc12 or also with other versions ?

**Comment by CelticMinstrel** [comment]
I don't know. Feel free to try them? Since they're C libraries, I could see them working on other versions... on the other hand, this is MSVC, so who knows.

**Comment by gfgtdf** [comment]
> I don't know. Feel free to try them? 

 i canot build wesnoth currently

> Since they're C libraries, I could see them working on other versions... on the other hand, this is MSVC, so who knows.

if they work on all other version please add them to other branches aswell in particular the master branch. (no need for vc10 and vc9 branch though sicne they are only for wesnoth 1.12)

**Comment by CelticMinstrel** [comment]
I can't verify that they work on other versions. If someone else verifies that though, perhaps I'll add them.

**Comment by CelticMinstrel** [comment]
Since wesnoth/wesnoth#990 is just about ready to merge, I wonder if someone could test that it builds with these files on MSVC 2015 and 2017?

**Comment by Wedge009** [comment]
Confirming I can build login_save_crypt with VS 2017 and this library.

**Comment by CelticMinstrel** [comment]
Great, now I just need confirmation for MSVC 2015... though if it works on 2013 and 2017 I'd be really surprised if it didn't work on 2015.

**Comment by CelticMinstrel** [comment]
Could @Wedge009 or @gfgtdf please also add these to the other branches now?

**Comment by Wedge009** [comment]
I copied your e1a3500 commit to VC14 and VC15 branches - I trust that's what you meant by other.

**Comment by CelticMinstrel** [comment]
Thanks!

**Pull request merged**
