### PR TITLE
Lib updates

### PR DESCRIPTION
**Pull request by Vultraz**
**Added**
- `libogg` (required by `libvorbis`)
- `libvorbis`
- `libvorbis-file`

**Updated**
- Boost (to 1.69, built in C++17 mode).
- SDL, SDL_Mixer, SDL_Image (DLL updates only)

### CODE REVIEW

**Comment by gfgtdf** [comment]
With c++17 enabled, will it still work with c++14?

**Comment by Vultraz** [comment]
I had no problems building 1.14 with these Boost libs, and that's using C++14.

**Comment by Wedge009** [comment]
What are you building with these days? Are we expected to use C++17 now?

For the additional SDL DLLs, where are you getting them from? My recollection is that I used whatever was supplied in the libsdl.org releases. Certainly fine with updating them if they need to be, but I'm curious as to the source (eg there are dozens of versions - even within the same version number - of zlib1.dll).

For ogg and vorbis, I used the most recent releases from xiph.org and compiled them myself (with VC15) when testing wesnoth/wesnoth#3851. I'll check if there are any discrepancies when I get home.

**Comment by Vultraz** [comment]
I got them from the official SDL, SDL_Image, and SDL_Mixer packages. Git says they differ from the ones already there. I don't actually know how 😬 But at the very least, you forgot the opus DLLs, which I have now added.

And no, you don't need to use C++17. I simply specified the `--std=c++17` flag when building Boost using the instructions in this repo. I had no problems building 1.14, but I admittedly hadn't had a chance to build master yet where I have C++17 mode explicitly enabled for our code (1.14 uses C++14 as mentioned above).

**Comment by Wedge009** [comment]
How bizarre... I just realised I never committed and pushed my boost 1.69 compilation - I had it all ready to go, but I think what happened was that I was waiting for my own Wesnoth compilation to finish first and then I would push the update... but I never did. (I use my own libraries for Wesnoth compilation rather than this one.)

Anyway, I decided not to push my own boost 1.69 build since this one is already done, and with C++17 enabled too. If it's enabled, should we make note of this in the read-me instructions? (My own build just follows those, no additional options enabled.) I know it's optional, but if it's a feature that we want/need perhaps it should be there.

On the SDL DLLs - I'm not sure why I didn't include the others. I'm aware that DLLs come from a variety of sources - I think even some of those that come with the official Wesnoth Windows build are different to the ones packaged here. I'll grant that libopus would be necessary for wesnoth/wesnoth#3773.

Lastly, the ogg/vorbis headers match what I downloaded so I assume the static libraries are fine. (I used the dynamic libraries for my own testing.)

So overall, I have no objections to this. If no-one else does, I think we can merge this.

Edit: If this is merged, @jyrkive's #32 and #33 should be as well.

**Comment by Wedge009** [comment]
I had second thoughts about the static ogg/vorbis libraries - see my comment in https://github.com/wesnoth/wesnoth/commit/86c2833f843b79ad8807bd528c248003e1eca5f3

Not a big deal, but just wondering if we should use the DLLs instead.

**Pull request merged**
