### PR TITLE
Update the GTK+ stack (VC12)

### PR DESCRIPTION
**Pull request by jyrkive**
I'm trying to fix [bug 25065](https://gna.org/bugs/?25065): credits don't show if text size is increased.

The problem is that the surface gets too large for Cairo to handle.

The fix I plan to make would involve the game detecting the situation and splitting the surface. However, the necessary error code was added in Cairo 1.10, and the version in this repository is older than that.

Thus, I updated Cairo to the latest version (self-built using https://github.com/wingtk/gvsbuild ). However, after updating Cairo, the game crashed on startup. Debugging showed that the game crashed inside Cairo after Pango had called a Cairo function. I figured that Pango is likely too old as well, and proceeded to update the entire GTK+ stack.

I have verified that the game launches and appears to run fine after this update, but only in the VC12 branch. (Verifying is impossible in VC14 and VC15 branches at the moment because VC14 is missing `boost/utility/string_view.hpp`, and Boost is severely incomplete in the VC15 branch.)

### CODE REVIEW

**Comment by Wedge009** [comment]
Hmm, I've been using Cairo 1.14.6 (current release at time of writing is 1.14.8) but pinched from a RPM package for mingw32. I self-build Pango (latest as at least a few days ago is 1.40.5) but that's about all I managed to build from GTK, but it looks so big and intertwined to me that I gave up on trying to extract only the bits that Wesnoth uses. So I just used the last official (and rather old) Win32 build release (which no longer exists because they direct Windows users to build it themselves now - and I never managed to get that working), which was gtk+-bundle_3.6.4-20130921_win32. I think this is what's used in this external package as well.

If you wish, I can merge this into VC12 since you believe it to be working, but I don't really know what to do for the later branches. I could try to import missing bits into them, but last time I tried to do that @aquileia had to clean up anyway so this time I followed the provided instructions precisely. So if they're missing things still, we need to find out what's missing and update the instructions as well.

**Comment by jyrkive** [comment]
@Wedge009 I can try updating Boost for this repository later this week.

**Comment by gfgtdf** [comment]
please don't foreget the master branch when you merge these changes.

**Comment by Wedge009** [comment]
I don't think I've ever touched master. What version is supposed to go in it?

**Comment by gfgtdf** [comment]
> I don't think I've ever touched master. What version is supposed to go in it?

i though the pangocairo  files of all 3 prs is the same and comatible with all vc versions ?

**Comment by jyrkive** [comment]
@gfgtdf  No, they're not. In every branch, I compiled the GTK+ stack with the appropriate version of the Visual Studio toolset.

**Comment by gfgtdf** [comment]
hmm but this is  a c library so they shodul be compatible, i mean the previous pangocairo library were also the same on all branches.

**Comment by jyrkive** [comment]
@gfgtdf Well, particularly HarfBuzz seems to be a problem. The DLL actually has a different name in different branches. It's **harfbuzz-vs12.dll** in the VC12 branch, but **harfbuzz-vs14.dll** in VC14 and VC15 branches.

**Pull request merged**
