### PR TITLE
Boost rebuild (VC14)

### PR DESCRIPTION
**Pull request by jyrkive**
Because Wesnoth now requires `boost/utility/string_view.hpp` when building with VS2015, and it would also be useful for my [pull request](https://github.com/wesnoth/wesnoth/pull/1028), I rebuilt Boost and ensured that `string_view` is now available. Also, because I was building Boost anyway, I went ahead and built 1.64, the latest stable version. (This repository currently has 1.62.)

In particular, merging this PR will fix the failing Appveyor builds.

I didn't rebuild/update Boost in the VC15 branch because it has `string_view` already.

### CODE REVIEW

**Comment by Wedge009** [comment]
Thanks for this. I only only wonder if the changes to the readme should be put in master - even if not all of those are needed for the earlier branches, it's what I work off for building boost for these branches.

Otherwise I'd merge this right away.

**Comment by Wedge009** [comment]
Bleh, just saw your PR on readme for master, and jyrkive already merged it.

**Comment by CelticMinstrel** [comment]
Um, that was me who merged it.

**Comment by Wedge009** [comment]
Yes, I realised that afterwards. I blame post-work exhaustion.

**Pull request merged**
