### PR TITLE
Add Discord Rich Presence lib (v2.1.1)

### PR DESCRIPTION
**Pull request by Vultraz**
I'm working on implementing Discord Rich Presence support. These apparently require the VC 2015 Redistributable, but I'm not sure where to note that.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I find that to be quite problematic. Currently, Windows releases are built against MinGW, which is probably the better option anyway. By requiring the VC 2015 redistributable, you're now referencing two entirely different versions of the same library (specifically, the standard C++ library). It's wasteful, frankly.

There are three options here.

1. My personal opinion would be to simply not do this in the first place, and continue to use MinGW.
2. It would of course also be possible to start building releases with MSVC. However, that might require finding a new packager. Since releases are bundled with an installer, end-user convenience isn't really affected.
3. If you really must have this feature, I'd suggest badgering Discord to release a MinGW-compatible version of their libraries. If you're lucky, they might even actually do it.

In any case, this absolutely cannot be done in 1.14 under any conditions.

------

I find that to be quite problematic. Currently, Windows releases are built against MinGW, which is probably the better option anyway. By requiring the VC 2015 redistributable, you're now referencing two entirely different versions of the same library (specifically, the standard C++ library). It's wasteful, frankly.

There are three options here.

1. My personal opinion would be to simply not do this in the first place, and continue to use MinGW.
2. It would of course also be possible to start building releases with MSVC. However, that might require finding a new packager. Since releases are bundled with an installer, end-user convenience isn't really affected.
3. If you really must have this feature, I'd suggest badgering Discord to release a MinGW-compatible version of their libraries. If you're lucky, they might even actually do it.

In any case, this absolutely cannot be done in 1.14 under any conditions.

------

P.S. I also don't actually know what Discord Rich Presence is or what benefits it could possibly bring, so I suggest you do try to elaborate on that at some point.

**Comment by Vultraz** [comment]
We can always build the libraries ourself. It's a quite small SDK. Also keep in mind this repo is for VS build dependencies, not MinGW's :P

**Comment by CelticMinstrel** [comment]
You can build the DRP libraries yourself? That sounds quite unlikely... as for your second point, that's true, so if there _is_ in fact MinGW-compatible version, then that renders part of my complaint moot.

**Comment by GregoryLundberg** [comment]
I, for one, have no interest in Discord chat in the game when playing. If I want to chat, which has a probability which is a good approximation of zero, I will use the Discord client.

I do not see a need for Discord support, but will not oppose it either. I would prefer to see Discord chat support as an add-on library (which we don't support). That way, when the next 'in' thing comes along, it, too, can be a player-chosen add-on.

That said, set aside your concerns.

The entire kit is on Github and MIT licensed, and can be built for any platform. This repo is a MSVC convenience and, if we're going to support direct in-game Discord support, the library should be here.

**Comment by GregoryLundberg** [comment]
Oof. Vultraz points out there is no chat. It's just about whether you're online. So I definitely, really, Really REALLY will never want to use the feature.

**Pull request closed without merging**
